### ISSUE TITLE
Outdated NPM installation

### ISSUE THREAD

**Issue by Piflyer** [ajhsu/chromecast-device-emulator#3]
Hi, I am trying to work with the Google Cast API, and happen to stumble upon this. I couldn't download it since this pops up `(node:5641) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead` Is there any way to work around it? Thanks.

**Comment by Piflyer** [comment]
I found a solution. Thanks!

**Comment by Piflyer** [comment]
In fact, the installation worked, but this happened `chromecast-device-emulator: { Error: Cannot find module '/home/pi/scenario.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Command.startEmulator (/usr/local/lib/node_modules/chromecast-device-emulator/dist/cli/app.js:15:27)
    at Command.listener (/usr/local/lib/node_modules/chromecast-device-emulator/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/local/lib/node_modules/chromecast-device-emulator/node_modules/commander/index.js:654:12)
    at Command.parse (/usr/local/lib/node_modules/chromecast-device-emulator/node_modules/commander/index.js:474:21) code: 'MODULE_NOT_FOUND' }
` Is there anything that I did wrong? Thanks.

**Comment by ajhsu** [comment]
Hi @Piflyer,
Not sure what's going on with your first issue. But if it happened again, would you please provided me a reproducible example for it? That would be helpful, thanks.

For your second issue, I believed that you just assigned a scenario json file that doesn't exist. Which means you have to pre-record a scenario json file from a real device OR you could just take the example from `examples/scenarios/example.json`.

To understand what's a scenario file, please refer to the README file for details: https://github.com/ajhsu/chromecast-device-emulator#what-is-a-scenario-json-file
